---
- name: Determine SSH port
  hosts: all
  gather_facts: no
  remote_user: root
  tasks:
    - name: "Check port {{ ansible_port }}"
      wait_for:
        port: "{{ ansible_port }}"
        state: "started"
        host: "{{ ansible_host }}"
        connect_timeout: "5"
        timeout: "5"
      delegate_to: "localhost"
      ignore_errors: "yes"
      register: ssh_port_result

    - name: "Check port 22"
      wait_for:
        port: "22"
        state: "started"
        host: "{{ ansible_host }}"
        connect_timeout: "5"
        timeout: "5"
      delegate_to: "localhost"
      ignore_errors: "yes"
      register: ssh_port_default
      when: 
        - ssh_port_result is defined 
        - ssh_port_result.state is undefined

    - name: Set SSH port to 22
      set_fact:
        ansible_port: "22"
      when: ssh_port_default.state is defined

    - name: Extract the correct SSH port
      set_fact:
        ansible_port: "{{ ssh_port }}"
      when: ssh_port_default.state is undefined


# Separate play for roles
- name: Run roles
  hosts: all
  gather_facts: yes
  become: yes
  roles: 
    - role: system
    - role: geerlingguy.pip
    - role: geerlingguy.docker
    - role: services